dependency-dir: ./src/

depends:
    - crc
    - serial-datagram:
        fork: Stapelzeiger
    - serial-can-bridge:
        fork: nuft
    - simplerpc


target.arm:
    - src/main.c
    - src/panic_log.c
    - src/sntp/sntp.c
    - src/commands.c
    - src/board/board.c
    - src/can_bridge.c
    - src/rpc_server.c
    - src/rpc_callbacks.c
    - src/msg_callbacks.c
    - src/uavcan_node.cpp
    - src/can-driver/src/uc_stm32_can.cpp
    - src/can-driver/src/uc_stm32_clock.cpp
    - src/can-driver/src/uc_stm32_thread.cpp

source:
    - src/timestamp.c

include_directories:
    - src/
    - src/board/


tests:
    - tests/unix-timestamp.cpp

templates:
    app_src.mk.jinja: app_src.mk
